## PostgreSQL Connection Configuration
spring.datasource.url=jdbc:postgresql://localhost:<db_port>/<insert_db_name_here>
spring.datasource.username=<username>
spring.datasource.password=<password>

spring.jpa.hibernate.ddl-auto=update

## JWT Secret String
secretJwtString=<minumum_32_characters_string_input_here>


